--- 
en-wp: 
  url: http://en.wikipedia.org/w/api.php
  pw: herb
  user: Jpatokal
commons: 
  url: http://commons.wikimedia.org/w/api.php
  pw: herb
  user: Jpatokal
en-wt: 
  url: http://wikitravel.org/wiki/en/api.php
  pw: herb
  user: Jpatokal
local:
  url: http://localhost/w/api.php
  pw: wombat
  user: Atlasmw
